apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-router-config
data:
  default.conf: |
    upstream aws_backend {
        server a14217039bd6f4767a6e3f99e069c4d6-167679785.ap-southeast-1.elb.amazonaws.com:80;
    }

    upstream gcp_backend {
        server 34.87.29.88:80;
    }

    map $backend $target {
        aws http://aws_backend;
        gcp http://gcp_backend;
    }

    server {
        listen 80;

        location / {
            proxy_pass $target;

            add_header X-Cloud-Provider $backend;
        }
    }
